### ISSUE TITLE
build inside alpine docker

### ISSUE THREAD

**Issue by esaheiskanen** [sfera-labs/iono-pi-c-lib#1]
Hi!
I would like to use iono utility in alpine based docker image. 

I have troublee building it. 

> bash-4.4# ./build
> === wiringPi ===
> wiringPi Build script
> =====================
> WiringPi Library
> [UnInstall]
> make: *** [Makefile:134: uninstall] Error 1

I also tried to install wiring pi with package manager but obviously it did not help as some libraries needed for building are missing. 

Any ideas how to build this succesfully?

Another option would be ready made docker image with iono utility. Docker image rith rest api would be even better!

**Comment by giampiero7** [comment]
Hi,
I just made a quick Google search - have you tried with this:
https://hub.docker.com/r/acencini/rpi-python-serial-wiringpi/
?
