### ISSUE TITLE
ionoPi setup error

### ISSUE THREAD

**Issue by abhinavrawat27** [sfera-labs/iono-pi-c-lib#2]
Hi

I have a ionoPi board and I have installed the latest Raspbian stretch image on it.
I have instaled the iono library using the below commands:

`sudo apt-get install git`
`git clone --recursive https://github.com/sfera-labs/iono-pi-c-lib.git`
`cd iono-pi-c-lib`
`sudo sh build`

The installation was successful and didn't show any errors. I have powered the board using 12v. When I am running the command `iono` it throws error `ionoPi setup error`.

How can I resolve it. Is it related to some hardware issues.?

**Comment by me6ran** [comment]
I have a same issue, may I know how you solve it?

**Comment by giampiero7** [comment]
@me6ran is the SPI interface enabled in raspi-config?

**Comment by me6ran** [comment]
oops, I had done, but when I checked it it was not enabled!!
I enable it again and it works fine.
Thank you.
