### ISSUE TITLE
Pulling up an input pin

### ISSUE THREAD

**Issue by me6ran** [sfera-labs/iono-pi-c-lib#3]
Hi,
I am trying to pull-up DI1-DI4 pins in order to catch the "float" and "low" state at the pins. But after pulling up, I dont have voltage on pins and also "iono di1" command gives me "low" instead of high.
I was wondering why pulling up is not working on digital input pins?

**Comment by giampiero7** [comment]
Hi,
How are you pulling up the DI? What's the voltage you read on the pin when pulled up?

**Comment by me6ran** [comment]
I went through 3 ways:

1- editing /boot/config.text
2- utilizing wiringPi library
3- utilizing Node-red 

I have tested the same pins and ways on merely RPi without ionoPi board. it  worked fine right away. I got 3.3 volts at input pins, and I could read the states of float and ground at input pins. 

But on iono, after pulling up the pins, I dont have voltage at pins. and also cannot read states of float and ground as result.

**Comment by giampiero7** [comment]
Yes, the internal pull-up of the RPi are bypassed by the electronics of the Iono Pi board.
Have a look at the schematics:
https://www.sferalabs.cc/files/ionopi/doc/ionopi-sch.pdf
You can see that the DI inputs are pulled down.

You could add an external 4K7 pull-up resistor (1/2W or 1W) between VSOUT and the DI or, if the voltage on the DI never exceeds 5V, you could use the TTL lines (moving the jumpers) which are pulled-up.
