### ISSUE TITLE
Node-RED

### ISSUE THREAD

**Issue by stefanoco** [sfera-labs/iono-pi-c-lib#4]
Hi we're starting using IonoPI for building demonstration applications. Surprisingly I'm not finding any useful reference to using Node-RED for controlling the available I/O. Before I start digging into schematics and documentation in order to find the right Raspberry pins etc. any example available?

**Comment by giampiero7** [comment]
Hello @stefanoco,
Controlling Iono Pi through Node-RED is pretty straightforward. All you need to look at is the GPIO mapping at page 13 of the [user guide](https://www.sferalabs.cc/files/ionopi/doc/ionopi-user-guide.pdf).
Alternatively, or if you want to use some other feature provided by the Iono Pi utility (e.g. 1wire), you can call it using the exec node.

**Comment by stefanoco** [comment]
Ok I see, very simple. Tested right now and confirm working by simply using the Raspberry GPIO Node-RED node.
