### ISSUE TITLE
ionoDigitallinterrupt and ionoPiSetDigitalDebounce --> SIGSEGV

### ISSUE THREAD

**Issue by DavideSfriso72** [sfera-labs/iono-pi-c-lib#6]
Hi,
I have a problem (SIGSEGV...) with ionoDigitallinterrupt, if the Debounce has been set (with ionoPiSetDigitalDebounce).

To reproduce, you have to:
- connect a switch to DI2
- compile iono_test_pt.c (gcc -Wall -o iono_test_pt iono_test_pt.c -lionoPi -lwiringPi -lpthread)
- launch iono_test_pt
- press the switch very fast and at least six or seven times
- wait 10 seconds
- press again the switch

I attach the possible patch; I stille have the doubt that the access to diConf->debounceThread has to be synchronised though mutex.

Ciao,
Davide.

[test and patch.zip](https://github.com/sfera-labs/iono-pi-c-lib/files/5760473/test.and.patch.zip)

**Comment by giampiero7** [comment]
Hi Davide,
Thanks for the report!
Could you explain what is the issue you are experiencing (errors or expected vs actual behaviour)?
Just to avoid me guessing wrong and for future reference.
Thanks!

**Comment by giampiero7** [comment]
Hi Davide,
Thanks for the report!
Would you like to submit a pull request? (to give you proper credit :))
And yes, it would need synchronisation though mutex.

Ciao,
Giampiero
